# Generated by Django 4.2.7 on 2025-10-12 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
        ('rankings', '0001_initial'),
        ('job_descriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_upgrade_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='requested_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests_to', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='upgraderequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='job_descriptions.jobdescription'),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rankingresult',
            index=models.Index(fields=['user', '-created_at'], name='ranking_res_user_id_e29be6_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingresult',
            index=models.Index(fields=['job_description'], name='ranking_res_job_des_8d05cf_idx'),
        ),
    ]
