# Generated by Django 4.2.7 on 2025-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Freemium', 'Freemium'), ('Starter', 'Starter'), ('Growth', 'Growth'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], max_length=50)),
                ('region', models.CharField(choices=[('Pakistan', 'Pakistan'), ('International', 'International'), ('Global', 'Global')], max_length=50)),
                ('billing_cycle', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('SixMonth', 'Six Month'), ('Annual', 'Annual')], max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('jd_limit', models.IntegerField(blank=True, help_text='Job Description limit (-1 or null for unlimited)', null=True)),
                ('cv_limit', models.IntegerField(blank=True, help_text='CV limit (-1 or null for unlimited)', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['region', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['name', 'region'], name='plans_name_b681a0_idx'), models.Index(fields=['is_active'], name='plans_is_acti_85d1d6_idx')],
                'unique_together': {('name', 'region', 'billing_cycle')},
            },
        ),
    ]
