# Generated by Django 4.2.7 on 2025-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Extracted text content from PDF')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-created_at'],
            },
        ),
    ]
