# Generated by Django 4.2.7 on 2025-10-12 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['user', 'status'], name='cvs_user_id_7acc10_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['user', '-created_at'], name='cvs_user_id_453963_idx'),
        ),
    ]
